source "https://rubygems.org"

# Jekyll
gem "jekyll", "~> 4.3.3"

# Themes
gem 'customtheme', path: './customtheme'

# Plugins
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end
gem 'jekyll-compose', group: [:jekyll_plugins]


# Windows and JRuby
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# Performance
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]